# Create the Base Image
FROM python:3.8.5-slim

# Copy requirements.txt file to the woking directory 
COPY requirements.txt /app/
WORKDIR /app

RUN apt-get update && apt-get install -y 
RUN pip install -r requirements.txt
COPY . /app

# Expose Streamlit port 8501
EXPOSE 8501

# Run the command
CMD ["streamlit", "run", "app.py"]